### ISSUE TITLE
How to deploy this code to SSRS 2016?

### ISSUE THREAD

**Issue by harrybook** [chathux/ssrs2016-form-authentication#1]
Hi Chathux,

Thank you very much for sharing this code.
I tried my best to search how to deploy this to SSRS 2016, but I failed.
SSRS 2016 has new portal, and there is no UILogon.aspx in this project.
Please tell me the deployment instructions.

Thanks,
Harry

**Comment by udayaw** [comment]
Harrybook, refer to this blog post for instructions.
[https://codeliteral.wordpress.com/2016/10/05/ssrs-2016-form-authentication/](url)

**Comment by harrybook** [comment]
Thanks, chathux.

I find a bug in  Authorization.cs,  the construction function should be static.

static Authorization()
        {
            InitializeMaps();
        }
